// app/page.tsx
"use client";
import Header from "@/components/Header";
import Progress, { Title } from "@/components/Progress";
import useProgressStore from "@/lib/hooks/useProgressStore";
import { update } from "@/lib/slices/progressSlice";
import { useEffect } from "react";
import { useDispatch } from "react-redux";

export default function Home() {
	const { yearProgress, monthProgress, dayProgress, hourProgress } = useProgressStore();
	const dispatch = useDispatch();

	// useEffect(() => {
	// 	dispatch(update());
	// }, [dispatch]);

	return (
		<>
			<Header />

			<main className="xl:grid xl:grid-cols-2 gap-4 mt-5">
				<Progress title={Title.year} progress={yearProgress} />
				<Progress title={Title.month} progress={monthProgress} />
				<Progress title={Title.day} progress={dayProgress} />
				<Progress title={Title.hour} progress={hourProgress} />
			</main>
		</>
	);
}

// app.vue
<script setup lang="ts">
useSeoMeta({
  title: "Year progress",
  description: "A website for tracking the progress of the current year visually",
});

useHead({
  bodyAttrs: {
    class: "xl:px-20 lg:px-16 md:px-10 sm:px-5 px-4 bg-zinc-300 dark:bg-stone-950 dark:text-slate-50 transition",
  },
});

const progress = useProgressStore();
</script>

<template>
  <main class="xl:grid xl:grid-cols-2 gap-4 mt-5">
    <Header />
    <Progress title="Year" :progress="progress.year" :update="progress.updateYear" />
    <Progress title="Month" :progress="progress.month" :update="progress.updateMonth" />
    <Progress title="Day" :progress="progress.day" :update="progress.updateDay" />
    <Progress title="Hour" :progress="progress.hour" :update="progress.updateHour" />
    <ToggleTheme />
  </main>
</template>
